# Generated by Django 4.1.3 on 2023-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobackhome',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videobackhome',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videobackhome',
            name='videofile',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
