# Generated by Django 4.1.3 on 2023-02-19 18:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_videobackhome_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobackhome',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
