# Generated by Django 4.1.3 on 2023-02-19 19:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_videobackhome_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobackhome',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
