# Generated by Django 4.1.3 on 2023-02-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_videobackhome_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videobackhome',
            old_name='content',
            new_name='body',
        ),
    ]
