# Generated by Django 4.1.3 on 2023-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_videobackhome_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobackhome',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videobackhome',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
