# Generated by Django 4.1.3 on 2023-02-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_rename_content_videobackhome_video_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videobackhome',
            old_name='Video_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='videobackhome',
            old_name='Video_is_published',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='videobackhome',
            old_name='Video_title',
            new_name='title',
        ),
    ]
